/*
 * AMALGAMATED C/C++ SOURCE FILE
 * Generated by Singleston v1.0.2
 * A powerful source file amalgamator for C/C++ projects
 *
 * Generation Date: 2025-11-21 16:15:40 UTC
 * Author: Adrien Soursou
 * Homepage: https://github.com/ChuOkupai/singleston
 *
 * This file contains the amalgamated source code from multiple
 * source files. It has been automatically generated and should
 * not be edited manually.
 *
 * Original project structure has been flattened into this single
 * file while preserving all functionality and dependencies.
 */

#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_mixer.h>
#include <SDL2/SDL_ttf.h>
#include <cmath>
#include <raylib.h>
#include <stdio.h>
#include <string>
#include <vector>

// === /home/raice/Documentos/BeloveEngine/include/engine/platforms/sdl/../../utils/color.hpp ===
/**
* @brief Color structure
* @param r integer for red value
* @param g integer for green value
* @param b integer for blue value
* @param a integer for alpha value
* @code
* // Example
* s_color blue = {0, 0, 255, 255};
* @endcode
*/
struct s_color {
    /**
    * @brief Red
    */
    unsigned int r = 0;

    /**
    * @brief Green
    */
    unsigned int g = 0;

    /**
    * @brief Blue
    */
    unsigned int b = 0;

    /**
    * @brief Alpha (transparency)
    */
    unsigned int a = 0;
};


// === /home/raice/Documentos/BeloveEngine/include/engine/platforms/sdl/../../utils/rect.hpp ===
/**
* @brief Structure for rect, 4 values
* @param x X coordinate for rect
* @param y Y coordinate for rect
* @param w width size for rect
* @param h height size for rect
* @code
* // Example:
* s_rect my_rect;
* my_rect.x = 8;
* my_rect.y = 8;
* my_rect.w = 16;
* my_rect.h = 16;
*
* Draw::draw_rectangle(my_rect.x, my_rect.y, my_rect.w, my_rect.h, blue);
* @endcode
*/
struct s_rect {
    /**
    * @brief X coordinate
    */
    int x;

    /**
    * @brief Y coordinate
    */
    int y;

    /**
    * @brief Width
    */
    int w;

    /**
    * @brief Height
    */
    int h;
};

// === /home/raice/Documentos/BeloveEngine/include/engine/platforms/sdl/font.hpp ===
struct s_font {
    TTF_Font *font;
    int size;
};

s_font load_font(const char* path, int base_size);
void unload_font(s_font font);

// === /home/raice/Documentos/BeloveEngine/include/engine/platforms/sdl/window.hpp ===

inline SDL_Renderer *sdl_renderer;
inline SDL_Window *sdl_window;

void window(int width, int height, const char* title);

void start_frametimer(int *start);

void end_frametimer(int start, int targetFPS);

void close_window();

// === /home/raice/Documentos/BeloveEngine/include/engine/platforms/sdl/audio.hpp ===

struct s_audio {
    Mix_Chunk *audio = NULL;
    int channel = -1;
    float duration;
};

s_audio load_audio(const char* path);
int play_audio(s_audio audio);
void pause_audio(s_audio& audio);
void resume_audio(s_audio& audio);
void stop_audio(s_audio& audio);
void free_audio(s_audio& audio);

// === /home/raice/Documentos/BeloveEngine/include/engine/utils/math.hpp ===

#define PI = 3.141592653
#define PI_2 = 1.5707963265
#define PI_3 = 1.047197551

/**
* @brief 2D Vector2 class
*/
struct vector2 {
    float x, y;

    /**
    * @brief Construct a new vector2 object
    * @param x float X coordinate
    * @param y float y coordinate
    */
    vector2(float x = 0, float y = 0) : x(x), y(y) {}

    /**
    * @brief Add two vectors
    * @param v Vector to add
    * @return vector2 Result of addition
    */
    vector2 operator+(const vector2& v) const { return vector2(x + v.x, y + v.y); }

    /**
    * @brief Subtract two vectors
    * @param v Vector to subtract
    * @return vector2 Result of subtraction
    */
    vector2 operator-(const vector2& v) const { return vector2(x - v.x, y - v.y); }

    /**
    * @brief Multiply two vectors
    * @param f Value to multiply in all axis
    * @return vector2 Result of multiply
    */
    vector2 operator*(float f) const { return vector2(x * f, y * f); }

    /**
    * @brief Multiply two vectors
    * @param v Vector to multiply
    * @return vector2 Result of multiplication
    */
    vector2 operator*(const vector2& v) const { return vector2(x * v.x, y * v.y); }

    /**
    * @brief Gets the length of the vector
    * @return float Length of vector
    */
    float length() const { return sqrt(x * x + y * y); }

    /**
    * @brief Normalizes the vector
    * @return vector2 Normalized vector
    */
    vector2 normalize() const { 
        float l = length(); 
        return l > 0 ? vector2(x/l, y/l) : vector2(0,0); 
    }
};

struct vector3 {
    float x, y, z;

    /**
    * @brief Construct a new vector3 object
    * @param x float X coordinate
    * @param y float y coordinate
    */
    vector3(float x = 0, float y = 0, float z = 0) : x(x), y(y), z(z) {}

    /**
    * @brief Add two vectors
    * @param v Vector to add
    * @return vector2 Result of addition
    */
    vector3 operator+(const vector3& v) const { return vector3(x + v.x, y + v.y, z + v.z); }

    /**
    * @brief Subtract two vectors
    * @param v Vector to subtract
    * @return vector2 Result of subtraction
    */
    vector3 operator-(const vector3& v) const { return vector3(x - v.x, y - v.y, z - v.z); }

    /**
    * @brief Multiply two vectors
    * @param f Value to multiply in all axis
    * @return vector2 Result of multiply
    */
    vector3 operator*(float f) const { return vector3(x * f, y * f, z * f); }

    /**
    * @brief Multiply two vectors
    * @param v Vector to multiply
    * @return vector2 Result of multiplication
    */
    vector3 operator*(const vector3& v) const { return vector3(x * v.x, y * v.y, z * v.z); }

    /**
    * @brief Gets the length of the vector
    * @return float Length of vector
    */
    float length() const { return sqrt(x * x + y * y + z * z); }

    /**
    * @brief Normalizes the vector
    * @return vector2 Normalized vector
    */
    vector3 normalize() const { 
        float l = length(); 
        return l > 0 ? vector3(x/l, y/l, z/l) : vector3(0,0,0); 
    }
};

// === /home/raice/Documentos/BeloveEngine/include/engine/utils/log.hpp ===

#define COLOR_RESET   "\033[0m"
#define COLOR_DEBUG   "\033[32m"
#define COLOR_LOG     "\033[0m"
#define COLOR_WARNING "\033[33m"
#define COLOR_ERROR   "\033[31m"
#define COLOR_FATAL   "\033[1;31;40m"

namespace Log {
    enum log_severity {
        SEVER_DEBUG,
        SEVER_LOG,
        SEVER_WARNING,
        SEVER_ERROR,
        SEVER_FATAL,
    };
    
    inline void log(const char* message, log_severity sever) {
        switch (sever) {
            case SEVER_DEBUG: {
                printf("%s[DEBUG] %s%s\n", COLOR_DEBUG, message, COLOR_RESET);
                break;
            }

            case SEVER_LOG: {
                printf("%s[LOG] %s%s\n", COLOR_LOG, message, COLOR_RESET);
                break;
            }

            case SEVER_WARNING: {
                printf("%s[WARNING] %s%s\n", COLOR_WARNING, message, COLOR_RESET);
                break;
            }

            case SEVER_ERROR: {
                printf("%s[ERROR] %s%s\n", COLOR_ERROR, message, COLOR_RESET);
                break;
            }
            
            case SEVER_FATAL: {
                printf("%s[FATAL] %s%s\n", COLOR_FATAL, message, COLOR_RESET);
                break;
            }

            default: {
                printf("%s[UNKNOWN] %s%s\n", COLOR_LOG, message, COLOR_RESET);
                break;
            }
        }
    }
}


// === /home/raice/Documentos/BeloveEngine/include/engine/platforms/sdl/texture.hpp ===


struct s_texture {
    SDL_Texture* tex = nullptr;
    int width = 0;
    int height = 0;
};

s_texture load_image(const char* path);
void unload_texture(s_texture& tex);

// === /home/raice/Documentos/BeloveEngine/include/engine/platforms/sdl/input.hpp ===

inline std::vector<SDL_GameController*> controllers;

enum key {
    key_UNKNOWN = 0,

    key_A, key_B, key_C, key_D, key_E, key_F, key_G, key_H, key_I, key_J,
    key_K, key_L, key_M, key_N, key_O, key_P, key_Q, key_R, key_S, key_T,
    key_U, key_V, key_W, key_X, key_Y, key_Z,

    key_0, key_1, key_2, key_3, key_4, key_5, key_6, key_7, key_8, key_9,

    key_F1, key_F2, key_F3, key_F4, key_F5, key_F6,
    key_F7, key_F8, key_F9, key_F10, key_F11, key_F12,

    key_ENTER, key_ESCAPE, key_SPACE, key_TAB, key_BACKSPACE,
    key_LEFT_SHIFT, key_RIGHT_SHIFT,
    key_LEFT_CTRL, key_RIGHT_CTRL,
    key_LEFT_ALT, key_RIGHT_ALT,

    key_UP, key_DOWN, key_LEFT, key_RIGHT,

    key_INSERT, key_DELETE, key_HOME, key_END,
    key_PAGE_UP, key_PAGE_DOWN,

    key_EQUAL, key_MINUS
};

enum controller_button {
    BUTTON_A = 0,
    BUTTON_B,
    BUTTON_X,
    BUTTON_Y,
    BUTTON_BACK,
    BUTTON_GUIDE,
    BUTTON_START,
    BUTTON_LEFTSTICK,
    BUTTON_RIGHTSTICK,
    BUTTON_LEFTSHOULDER,
    BUTTON_RIGHTSHOULDER,
    BUTTON_DPAD_UP,
    BUTTON_DPAD_DOWN,
    BUTTON_DPAD_LEFT,
    BUTTON_DPAD_RIGHT
};

enum controller_axis {
    AXIS_LEFT_X,
    AXIS_LEFT_Y,
    AXIS_RIGHT_X,
    AXIS_RIGHT_Y,
    AXIS_TRIGGER_LEFT,
    AXIS_TRIGGER_RIGHT,
};

enum mouse_button {
    MOUSE_LEFT = 0,
    MOUSE_RIGHT = 1,
    MOUSE_MIDDLE = 2,
};

namespace Input {
    void init();
    void update();
    bool is_pressed(key keycode);
    bool is_pressed_gamepad(controller_button btn);
    bool is_released(key keycode);
    bool is_released_gamepad(controller_button btn);
    bool is_down(key keycode);
    bool is_down_gamepad(controller_button btn);
    float get_axis(controller_axis btn);
    key backend_to_key(SDL_Scancode keycode);
    SDL_Scancode key_to_backend(key keycode);

    int get_mouse_x();
    int get_mouse_y();

    bool is_mouse_down(mouse_button btn);
    bool is_mouse_pressed(mouse_button btn);
}

// === /home/raice/Documentos/BeloveEngine/include/engine/platforms/sdl/draw.hpp ===

namespace Draw {
    void draw_rectangle(int posX, int posY, int width, int height, s_color color);

    void draw_text(s_font font, const char* text, int x, int y, int size, s_color color);

    void clear(s_color color);
    
    void draw_rect(int x, int y, int w, int h, s_color color);
    
    void draw_line(int x1, int y1, int x2, int y2, s_color color);
    
    void draw_texture(const s_texture& texture, int x, int y);

    void draw_texture_ex(const s_texture& texture, int x, int y, int w, int h, s_rect srcrect, float rotation);
}

// === /home/raice/Documentos/BeloveEngine/include/engine/platform.hpp ===

#ifndef PLAT_RAYLIB
    #ifndef PLAT_FRAMEBUFFER
        #define PLAT_SDL
    #endif
#endif

#ifdef PLAT_RAYLIB
#endif

#ifdef PLAT_SDL
#endif

#ifdef PLAT_FRAMEBUFFER
#endif

// === /home/raice/Documentos/BeloveEngine/source/engine.hpp ===

class Engine {
public:
    Engine(int width, int height, const std::string& title);
    virtual ~Engine();

    bool init();
    void run();

protected:
    virtual void ready() {}
    virtual void update() {}
    virtual void render() {}
    virtual void handleInput();

    int width, height;
    std::string title;
    bool running;
};


// === /home/raice/Documentos/BeloveEngine/source/engine.cpp ===

Engine::Engine(int w, int h, const std::string& t)
    : width(w), height(h), title(t), running(false) {}

Engine::~Engine() {
    close_window();
}

bool Engine::init() {
    Input::init();
    window(width, height, title.c_str());
    running = true;
    ready();
    return true;
}

void Engine::handleInput() {
    Input::update();
}

void Engine::run() {
    int frame_start;
    while (running) {
        start_frametimer(&frame_start);

        handleInput();
        update();
// HACK: quick fix for rendering in raylib (start rendering)
#ifdef PLAT_RAYLIB
        BeginDrawing();
#endif
        render();

// HACK: quick fix for rendering in sdl
#ifdef PLAT_SDL
        SDL_RenderPresent(sdl_renderer);
#endif
        end_frametimer(frame_start, 60);
// HACK: quick fix for rendering in raylib (end rendering)
#ifdef PLAT_RAYLIB
        EndDrawing();
#endif

    }
}

